"""Template loading utilities for the ``eaap`` CLI.

The ``eaap init`` command reads a directory tree of templates packaged
under :mod:`ai_core.cli.templates.init` and renders each one. The
``eaap generate`` commands use compact inline templates kept in this
module so test authors can grep for a single source of truth.
"""

from __future__ import annotations

from collections.abc import Iterator
from importlib import resources
from typing import Any

from jinja2 import Environment

INIT_TEMPLATE_PACKAGE = "ai_core.cli.templates.init"


def render_template(env: Environment, body: str, context: dict[str, Any]) -> str:
    """Render ``body`` (a Jinja2 template) with ``context``."""
    return env.from_string(body).render(**context)


def iter_template_files(package: str) -> Iterator[tuple[str, str]]:
    """Yield ``(relative_path, template_body)`` for every text resource in ``package``.

    Walks the package recursively. ``relative_path`` uses POSIX-style
    forward slashes regardless of host platform — callers can join it
    onto a :class:`pathlib.Path` directly.
    """
    root = resources.files(package)

    def _walk(traversable: Any, prefix: str) -> Iterator[tuple[str, str]]:
        for entry in sorted(traversable.iterdir(), key=lambda e: e.name):
            name = entry.name
            if name in {"__init__.py", "__pycache__"}:
                continue
            rel = f"{prefix}{name}" if prefix == "" else f"{prefix}/{name}"
            if entry.is_dir():
                yield from _walk(entry, rel)
            else:
                yield rel, entry.read_text(encoding="utf-8")

    yield from _walk(root, "")


# ---------------------------------------------------------------------------
# Inline agent templates
# ---------------------------------------------------------------------------
_AGENT_PY = '''"""{{ class_name }} — generated by `eaap generate agent {{ agent_name }}`."""

from __future__ import annotations

from collections.abc import Mapping, Sequence
from typing import Any

from ai_core.agents import BaseAgent


class {{ class_name }}(BaseAgent):
    """LangGraph agent scaffolded by `eaap generate agent`."""

    agent_id: str = "{{ agent_id }}"

    def system_prompt(self) -> str:
        """Return the agent's system prompt — edit me."""
        return (
            "You are {{ class_name }}, an enterprise agent. "
            "Follow the user's instructions, use available tools when "
            "appropriate, and stop as soon as the task is done."
        )

    def tools(self) -> Sequence[Mapping[str, Any]]:
        """Return tool definitions in OpenAI-compatible format."""
        return ()
'''

_AGENT_TEST_PY = '''"""Smoke test for {{ class_name }}."""

from __future__ import annotations

from unittest.mock import AsyncMock

import pytest

from ai_core.agents import MemoryManager
from ai_core.config.settings import AppSettings
from ai_core.di import Container, AgentModule
from ai_core.di.interfaces import ILLMClient, LLMResponse, LLMUsage
from ai_core.observability import NoOpObservabilityProvider
from {{ module_path }} import {{ class_name }}


pytestmark = pytest.mark.unit


@pytest.fixture
def container(monkeypatch: pytest.MonkeyPatch) -> Container:
    settings = AppSettings(service_name="{{ agent_id }}-test")

    fake_llm = AsyncMock(spec=ILLMClient)
    fake_llm.complete = AsyncMock(
        return_value=LLMResponse(
            model="fake/model",
            content="ok",
            tool_calls=[],
            usage=LLMUsage(prompt_tokens=1, completion_tokens=1, total_tokens=2),
            raw={},
        )
    )

    from injector import Module, provider, singleton

    class _Overrides(Module):
        @singleton
        @provider
        def provide_llm(self) -> ILLMClient:
            return fake_llm

    return Container.build([AgentModule(settings=settings), _Overrides()])


def test_agent_constructs(container: Container) -> None:
    agent = container.get({{ class_name }})
    assert agent.agent_id == "{{ agent_id }}"
    assert isinstance(agent.system_prompt(), str)


def test_agent_compiles(container: Container) -> None:
    agent = container.get({{ class_name }})
    graph = agent.compile()
    assert graph is not None
'''


AGENT_TEMPLATES: dict[str, str] = {
    "{{ agent_name }}.py": _AGENT_PY,
    "test_{{ agent_name }}.py": _AGENT_TEST_PY,
}


# ---------------------------------------------------------------------------
# Inline MCP templates
# ---------------------------------------------------------------------------
_MCP_PY = '''"""{{ class_prefix }} MCP server — generated by `eaap generate mcp {{ server_name }}`."""

from __future__ import annotations

from pydantic import BaseModel, Field

try:
    from fastmcp import FastMCP
except ImportError as exc:
    raise ImportError(
        "fastmcp must be installed to run this MCP server. "
        "`pip install fastmcp`"
    ) from exc


server = FastMCP("{{ server_name }}")


class {{ class_prefix }}EchoIn(BaseModel):
    """Input payload for the example {{ tool_name }} tool."""

    message: str = Field(..., description="Text to echo back.")


class {{ class_prefix }}EchoOut(BaseModel):
    """Result payload returned by the example {{ tool_name }} tool."""

    echoed: str


@server.tool()
async def {{ tool_name }}(payload: {{ class_prefix }}EchoIn) -> {{ class_prefix }}EchoOut:
    """Echo the supplied message back — replace with real logic."""
    return {{ class_prefix }}EchoOut(echoed=payload.message)


def main() -> None:
    """Run the MCP server over stdio."""
    server.run()


if __name__ == "__main__":
    main()
'''

_MCP_TEST_PY = '''"""Smoke test for the {{ server_name }} MCP server."""

from __future__ import annotations

import pytest

from {{ module_path }} import (
    {{ class_prefix }}EchoIn,
    {{ class_prefix }}EchoOut,
    {{ tool_name }},
)


pytestmark = pytest.mark.unit


async def test_{{ tool_name }}_round_trip() -> None:
    result = await {{ tool_name }}({{ class_prefix }}EchoIn(message="hi"))
    assert isinstance(result, {{ class_prefix }}EchoOut)
    assert result.echoed == "hi"
'''


MCP_TEMPLATES: dict[str, str] = {
    "{{ server_name }}.py": _MCP_PY,
    "test_{{ server_name }}.py": _MCP_TEST_PY,
}


__all__ = [
    "AGENT_TEMPLATES",
    "INIT_TEMPLATE_PACKAGE",
    "MCP_TEMPLATES",
    "iter_template_files",
    "render_template",
]
